server:
  port: 8080


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.laochou.diagnose.pojo
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddiagnose?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: laochou
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      location: F:/JAVA/CloudDiagnose/src/main/resources/static
      # 文件
      max-file-size: -1
      max-request-size: -1

  resources:
    static-locations: classpath:static/, file:${spring.servlet.multipart.location}